### ISSUE TITLE
misleading  pairwise distances implementation.

### ISSUE THREAD

**Issue by lc82111** [omoindrot/tensorflow-triplet-loss#12]
I think below line is some misleading. 
[https://github.com/omoindrot/tensorflow-triplet-loss/blob/master/model/triplet_loss.py#L29](url)
Instead of `distances = tf.expand_dims(square_norm, 0) - 2.0 * dot_product + tf.expand_dims(square_norm, 1)` ,  I prefer
`distances = tf.expand_dims(square_norm, 1) - 2.0 * dot_product + tf.expand_dims(square_norm, 0)` , which is more consisten with ||a - b||^2 = ||a||^2  - 2 <a, b> + ||b||^2.

**Comment by omoindrot** [comment]
Done :)

**Comment by lc82111** [comment]
Well done :)
