### ISSUE TITLE
The following error occurred when I ran train.py

### ISSUE THREAD

**Issue by wisewolf7** [omoindrot/tensorflow-triplet-loss#19]
TypeError: Expected binary or unicode string, got <PrefetchDataset shapes: ((?, 784), (?,)), types: (tf.float32, tf.int32)>

**Comment by omoindrot** [comment]
Maybe check your version of TensorFlow?
Otherwise can you post the full trace of the error.

**Comment by alexandreduhamel** [comment]
Hi, from clean AWS Deep Learning AMI (tf version 1.4.1) and without specify data directory (default)

> Traceback (most recent call last):
  File "train.py", line 40, in <module>
    estimator.train(lambda: train_input_fn(args.data_dir, params))
  File "/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 302, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 711, in _train_model
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 694, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/ec2-user/work/tensorflow-triplet-loss/model/model_fn.py", line 59, in model_fn
    images = tf.reshape(images, [-1, params.image_size, params.image_size, 1])
  File "/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3938, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 513, in _apply_op_helper
    raise err
TypeError: Failed to convert object of type <class 'tensorflow.python.data.ops.dataset_ops.PrefetchDataset'> to Tensor. Contents: <PrefetchDataset shapes: ((?, 784), (?,)), types: (tf.float32, tf.int32)>. Consider casting elements to a supported type.

**Comment by omoindrot** [comment]
You need version 1.6 at least because the `train` method of an estimator can accept a `tf.data.Dataset` as input only since v1.6.

**Comment by alexandreduhamel** [comment]
On version 1.11.0, it works, thanks !

**Comment by SaintLogos1234** [comment]
I meet some problem, but I don't upgrade my tensorflow, because My cuda is version8,what can I do ?

**Comment by omoindrot** [comment]
Just return tensors instead of just a dataset in the input functions:

```python
def train_input_fn(data_dir, params):
    """Train input function for the MNIST dataset.
    Args:
        data_dir: (string) path to the data directory
        params: (Params) contains hyperparameters of the model (ex: `params.num_epochs`)
    """
    dataset = ...
    dataset = dataset.prefetch(1)  # make sure you always have one batch ready to serve
    
    iterator = dataset.make_one_shot_iterator()
    features, labels = iterator.get_next()
    return features, labels
```

**Comment by SaintLogos1234** [comment]
This problem has been solved. Thank you very much

**Comment by SaintLogos1234** [comment]
I run pytest, following error occurred：
============================= test session starts ==============================
platform linux -- Python 3.6.5, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: /home/xieyangyang/Downloads/tensorflow-triplet-loss-master, inifile:
plugins: remotedata-0.2.1, openfiles-0.3.0, doctestplus-0.1.3, arraydiff-0.2
collected 0 items / 1 errors                                                   

==================================== ERRORS ====================================
______________ ERROR collecting model/tests/test_triplet_loss.py _______________
ImportError while importing test module '/home/xieyangyang/Downloads/tensorflow-triplet-loss-master/model/tests/test_triplet_loss.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py:58: in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
../../anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py:28: in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
../../anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py:24: in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
../../anaconda3/lib/python3.6/imp.py:243: in load_module
    return load_dynamic(name, filename, file)
../../anaconda3/lib/python3.6/imp.py:343: in load_dynamic
    return _load(spec)
E   ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:
model/tests/test_triplet_loss.py:4: in <module>
    import tensorflow as tf
../../anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py:24: in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
../../anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py:49: in <module>
    from tensorflow.python import pywrap_tensorflow
../../anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py:74: in <module>
    raise ImportError(msg)
E   ImportError: Traceback (most recent call last):
E     File "/home/xieyangyang/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
E       from tensorflow.python.pywrap_tensorflow_internal import *
E     File "/home/xieyangyang/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
E       _pywrap_tensorflow_internal = swig_import_helper()
E     File "/home/xieyangyang/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
E       _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
E     File "/home/xieyangyang/anaconda3/lib/python3.6/imp.py", line 243, in load_module
E       return load_dynamic(name, filename, file)
E     File "/home/xieyangyang/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
E       return _load(spec)
E   ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
E   
E   
E   Failed to load the native TensorFlow runtime.
E   
E   See https://www.tensorflow.org/install/errors
E   
E   for some common reasons and solutions.  Include the entire stack trace
E   above this error message when asking for help.
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.14 seconds ===========================
 how to solve

**Comment by omoindrot** [comment]
Looks like an error from your TensorFlow installation.

The error you have looks like the one in [this GitHub issue](https://github.com/tensorflow/tensorflow/issues/15604).

**Comment by SaintLogos1234** [comment]
It is not a problem with my tensorflow installation, it is just because my version of tensorflow is 1.4.0, but the minimum requirement for this code version of tensorflow is 1.6.0

**Comment by omoindrot** [comment]
Great I'm closing the issue then.
