### ISSUE TITLE
Bug reply

### ISSUE THREAD

**Issue by ymcasky** [omoindrot/tensorflow-triplet-loss#3]
In test_triplet_mask

distinct = (i != j and i != j and j != k) should be
distinct = (i != j and i != k and j != k)

Thanks for your contribution!

**Comment by omoindrot** [comment]
You are right, the mistake is also in other test functions. It still works because we make sure that i and k have different labels so they must be distinct.

Could you correct this in a pull request?

**Comment by omoindrot** [comment]
Solved in #4
