### ISSUE TITLE
Dead link 

### ISSUE THREAD

**Issue by mquillot** [omoindrot/tensorflow-triplet-loss#34]
Hi ! A dead link is on the repo's readme : 
When I click on the link "params.json", i arrive on this page: https://github.com/omoindrot/tensorflow-triplet-loss/blob/master/experiments/base_model/params.json

i propose to switch the link with the following (or a new one): 
https://github.com/omoindrot/tensorflow-triplet-loss/blob/master/experiments/batch_all/params.json

I hope my english is enough good.
Best regards.

**Comment by omoindrot** [comment]
Done thanks.
