### ISSUE TITLE
For market data

### ISSUE THREAD

**Issue by mahfujau** [omoindrot/tensorflow-triplet-loss#8]
Can you release the code for market1501 dataset, please?

**Comment by omoindrot** [comment]
You mean adapt the code for MNIST to make it work with the market1501 dataset?

I would encourage you to do it yourself and maybe submit a pull request?

**Comment by bzhong2** [comment]
Is there any example of importing custom dataset?

**Comment by omoindrot** [comment]
If you want to use your own dataset, you just need to create an input function that returns a dataset containing (image, label) pairs, just like in [`model/input_fn.py`][1].

You can check a tutorial on creating TensorFlow Datasets here: https://www.tensorflow.org/programmers_guide/datasets



[1]: https://github.com/omoindrot/tensorflow-triplet-loss/blob/master/model/input_fn.py

**Comment by cxfire16** [comment]
Hi @omoindrot, to what I've understood the `model/input_fn.py` just seems to feed data into the model which makes me think that it's the `mnist_dataset.py` that we should create to be able to adapt other datasets. Am I understanding it correctly? btw, thanks for pointing out the guide to creating input pipelines! huge help! thanks!

**Comment by omoindrot** [comment]
@cxfire16: As long as you create a `tf.data.Dataset` (as described in the [dataset guide][1]) and return it in the input function you should be good.

You should also look at the [estimator guide][2] to understand more about the input functions you need.

The `mnist_dataset.py` file is taken from the official TensorFlow repo ([here][3]) and downloads the TFRecords files for MNIST and create a dataset.

You don't need to go through TFRecords to work on your own dataset, you can just build a simple input function with `tf.data` and use it in the estimator.


[1]: https://www.tensorflow.org/programmers_guide/datasets
[2]: https://www.tensorflow.org/guide/estimators
[3]: https://github.com/tensorflow/models/blob/master/official/mnist/dataset.py

**Comment by cxfire16** [comment]
That's noted! Thanks!
